# Generated by Django 5.2.13 on 2026-05-21 15:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0007_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('review', models.CharField(blank=True, max_length=1023, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.user')),
            ],
        ),
    ]
