# Generated by Django 5.2.13 on 2026-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=8191, null=True),
        ),
    ]
