# Generated by Django 5.2.13 on 2026-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0009_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='wiki_id',
            field=models.CharField(default='N/A', unique=True),
            preserve_default=False,
        ),
    ]
