# Generated by Django 5.2.13 on 2026-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0010_item_wiki_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='wiki_id',
        ),
        migrations.AddField(
            model_name='film',
            name='trakt_id',
            field=models.IntegerField(default=12345, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
