# Generated by Django 5.2.13 on 2026-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0011_remove_item_description_remove_item_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trakt_slug',
            field=models.CharField(default='house-1977', unique=True),
            preserve_default=False,
        ),
    ]
