# Generated by Django 5.2.13 on 2026-05-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0012_film_trakt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='title',
            field=models.CharField(default='House'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=1977),
            preserve_default=False,
        ),
    ]
