# Generated by Django 5.2.13 on 2026-05-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0013_film_title_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(null=True),
        ),
    ]
