# Generated by Django 5.2.13 on 2026-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0014_film_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trakt_id',
        ),
        migrations.AddField(
            model_name='film',
            name='trakt_url',
            field=models.URLField(null=True),
        ),
    ]
