# Generated by Django 5.2.13 on 2026-05-25 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0015_remove_film_trakt_id_film_trakt_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='trakt_url',
        ),
    ]
