# Generated by Django 5.2.13 on 2026-05-25 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0016_remove_film_trakt_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trakt_slug', models.CharField(unique=True)),
                ('name', models.CharField()),
                ('headshot_url', models.URLField(null=True)),
                ('birth', models.DateField(null=True)),
                ('death', models.DateField(null=True)),
                ('biography', models.CharField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
