# Generated by Django 5.2.13 on 2026-05-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0017_crew'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewDirectedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.crew')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.film')),
            ],
        ),
    ]
