# Generated by Django 5.2.13 on 2026-05-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0018_crewdirectedfilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='item',
        ),
        migrations.RemoveField(
            model_name='film',
            name='trakt_slug',
        ),
    ]
