# Generated by Django 5.2.13 on 2026-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0019_remove_crew_item_remove_film_trakt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trakt_slug',
            field=models.CharField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
