# Generated by Django 5.2.13 on 2026-05-25 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0020_film_trakt_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crew',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
