# Generated by Django 5.2.13 on 2026-05-26 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0022_alter_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='next_fetch',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='next_fetch',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
