# Generated by Django 5.2.13 on 2026-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0023_crew_next_fetch_film_next_fetch'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='next_interval',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='film',
            name='next_interval',
            field=models.IntegerField(default=6),
        ),
    ]
