# Generated by Django 5.2.13 on 2026-05-26 13:49

import cheeserate_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0024_crew_next_interval_film_next_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='last_fetched',
            field=models.DateTimeField(default=cheeserate_app.models.ancient_time),
        ),
        migrations.AddField(
            model_name='film',
            name='last_fetched',
            field=models.DateTimeField(default=cheeserate_app.models.ancient_time),
        ),
    ]
