# Generated by Django 5.2.13 on 2026-05-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0025_crew_last_fetched_film_last_fetched'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewStarringFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.crew')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheeserate_app.film')),
            ],
        ),
    ]
