# Generated by Django 5.2.13 on 2026-05-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0026_crewstarringfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewstarringfilm',
            name='cast_as',
            field=models.CharField(null=True),
        ),
    ]
