# Generated by Django 5.2.13 on 2026-05-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0027_crewstarringfilm_cast_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='biography',
            field=models.CharField(null=True),
        ),
    ]
