# Generated by Django 5.2.13 on 2026-05-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0028_film_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='biography',
            new_name='overview',
        ),
    ]
