# Generated by Django 5.2.13 on 2026-05-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0029_rename_biography_film_overview'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='crewdirectedfilm',
            constraint=models.UniqueConstraint(fields=('director', 'film'), name='unique_directing'),
        ),
        migrations.AddConstraint(
            model_name='crewstarringfilm',
            constraint=models.UniqueConstraint(fields=('cast', 'film', 'cast_as'), name='unique_casting'),
        ),
    ]
