# Generated by Django 5.2.13 on 2026-05-29 08:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0030_crewdirectedfilm_unique_directing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='item',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='item',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='score_avg',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='film',
            name='score_sum',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
