# Generated by Django 5.2.13 on 2026-05-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0031_remove_film_item_remove_rating_item_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='crewstarringfilm',
            name='unique_casting',
        ),
        migrations.RemoveField(
            model_name='crewstarringfilm',
            name='cast_as',
        ),
        migrations.AddConstraint(
            model_name='crewstarringfilm',
            constraint=models.UniqueConstraint(fields=('cast', 'film'), name='unique_casting'),
        ),
    ]
