# Generated by Django 5.2.13 on 2026-05-31 04:01

from django.db import migrations

def delete_rows(apps, scheme_editor):
    model = apps.get_model('cheeserate_app', 'user')
    model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0032_remove_crewstarringfilm_unique_casting_and_more'),
    ]

    operations = [
        migrations.RunPython(
            delete_rows
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
