# Generated by Django 5.2.13 on 2026-06-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheeserate_app', '0033_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='next_interval',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='film',
            name='next_interval',
            field=models.IntegerField(default=12),
        ),
    ]
